### ISSUE TITLE
Колчество просмотров +2

### ISSUE THREAD

**Issue by supaweb** [artdevue/HitsPage#1]
При перезагрузке страницы добавляется +2 просмотра, а не +1. Наблюдения на тестовом сайте.
Google Chrome Версия 24.0.1312.57, Windows Server 2008 R2

**Comment by artdevue** [comment]
Я не тестировал на  Windows Server и не могу проверить в чём ошибка.
Я обновил версию, попробуйте сейчас.

**Comment by supaweb** [comment]
Это конечно к самому скрипту видимо не имеет отношения, но для заметки, может будет полезно. Перепроверил, в Хроме осталось так же. Firefox и Explorer добавляют +1, как и положено. Причем после того как в файерфоксе добавляет +1, переключить в Хром, то после первой перезагрузке, он тоже сделает +1, но в дальнейших перезагрузках страницы опять +2 будет. Видимо это какие-то Хромовские штуки с кешированием.

**Comment by artdevue** [comment]
странно честно говоря, возьму на заметку, но такого пока больше нигде не наблюдалось.
Возможные причины - у вас идёт редирект на саму страницу. т.е. двойной вызов ресурса.... даже не знаю, что и ответить.
В любом случае спасибо за коммент.
